### ISSUE TITLE
Pico maps are wrong

### ISSUE THREAD

**Issue by jon672** [hdboye/FnfModAttempt2#1]
in multiple (i think maybe all that arent remapped?) pico (the song not the whole week) has the wrong map. its some random like 30 second thing then the rest of the song is nothing. its not a problem with the mod because its multiple different mods only on this site

**Comment by FunniestGuy** [comment]
yes this is true, its alot of spam then ends mid way

**Comment by hdboye** [comment]
it's weird i removed that shit couple of months ago but its still there :/ prob made sum kinda mistake i'll get to it ltr

**Comment by hdboye** [comment]
site updates ended
